package com.myspace.myproject;

/**
 * This class was automatically generated by the data modeler tool.
 * Este es un nuevo comentario 
 * Otro comment, otro, uno mas, uno mas, >_<, a ver
*/

public class MiClase implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String nombre;

	public MiClase() {
	}

	public java.lang.String getNombre() {
		return this.nombre;
	}

	public void setNombre(java.lang.String nombre) {
		this.nombre = nombre;
	}

	public MiClase(java.lang.String nombre) {
		this.nombre = nombre;
	}

}
